// GET req api/auth
GET http://localhost:3000/api/auth HTTP/1.1

###
// GET req api/auth/token
GET http://localhost:3000/api/auth/token HTTP/1.1

###
// POST req api/auth
POST http://localhost:3000/api/auth HTTP/1.1
Content-Type: application/json

{
  "email": "luquiitas.f@gmail.com"
}

###
// POST req api/auth/token
POST http://localhost:3000/api/auth/token HTTP/1.1
Content-Type: application/json

{
  "email": "luquiitas.f@gmail.com",
  "code": "362862"
}
###
// GET req api/me
GET http://localhost:3000/api/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1cXVpaXRhcy5mQGdtYWlsLmNvbSIsInVzZXJJZCI6IjMzODY1ZDJmLTU5NmYtNDY3My1hMzIyLTEyNWRmNDE0YjJjOSIsImlhdCI6MTc1ODEwNzIyNX0.Rv0DiSclFTxYikpD2rtNv5JWX8OGpek7NoBLjoDPsLE

###
// PATCH req api/me
PATCH http://localhost:3000/api/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1cXVpaXRhcy5mQGdtYWlsLmNvbSIsInVzZXJJZCI6IjMzODY1ZDJmLTU5NmYtNDY3My1hMzIyLTEyNWRmNDE0YjJjOSIsImlhdCI6MTc1ODEwNzIyNX0.Rv0DiSclFTxYikpD2rtNv5JWX8OGpek7NoBLjoDPsLE
Content-Type: application/json

{
  "name": "Lucas Fzz"
}

###
// PATCH req api/me/address
PATCH http://localhost:3000/api/me/address HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1cXVpaXRhcy5mQGdtYWlsLmNvbSIsInVzZXJJZCI6IjMzODY1ZDJmLTU5NmYtNDY3My1hMzIyLTEyNWRmNDE0YjJjOSIsImlhdCI6MTc1ODEwNzIyNX0.Rv0DiSclFTxYikpD2rtNv5JWX8OGpek7NoBLjoDPsLE
Content-Type: application/json

{
  "address": {
    "street": "Calle Falsa 555",
    "city": "Corvaro",
    "state": "L'Aquila",
    "postalCode": "67050",
    "country": "Italia"
  }

}

###
// GET req api/products/[id]
GET http://localhost:3000/api/products/50b46a72-e0c9-49fe-b6bc-8f6999d1bcc1 HTTP/1.1

###