// GET req api/auth
GET http://localhost:3000/api/auth HTTP/1.1

###
// GET req api/auth/token
GET http://localhost:3000/api/auth/token HTTP/1.1

###
// POST req api/auth
POST http://localhost:3000/api/auth HTTP/1.1
Content-Type: application/json

{
  "email": "luquiitas.f@gmail.com"
}

###
// POST req api/auth/token
POST http://localhost:3000/api/auth/token HTTP/1.1
Content-Type: application/json

{
  "email": "luquiitas.f@gmail.com",
  "code": "134622"
}
###
// GET req api/me
GET http://localhost:3000/api/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1cXVpaXRhcy5mQGdtYWlsLmNvbSIsInVzZXJJZCI6IjMzODY1ZDJmLTU5NmYtNDY3My1hMzIyLTEyNWRmNDE0YjJjOSIsImlhdCI6MTc1ODA2Nzg3MH0.VRVfNT3BM-xTAQ47daONl1EOz7wxCjqH3QC1YAS4HUM
###

// PATCH req api/me
PATCH http://localhost:3000/api/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1cXVpaXRhcy5mQGdtYWlsLmNvbSIsInVzZXJJZCI6IjMzODY1ZDJmLTU5NmYtNDY3My1hMzIyLTEyNWRmNDE0YjJjOSIsImlhdCI6MTc1ODA2Nzg3MH0.VRVfNT3BM-xTAQ47daONl1EOz7wxCjqH3QC1YAS4HUM
Content-Type: application/json

{
  "name": "Lucas Quiroz",
  "address": {
    "street": "Calle Falsa 123",
    "city": "Springfield",
    "state": "IL",
    "postalCode": "62704",
    "country": "USA"
  }

}

###
